### ISSUE TITLE
Unit 4 has incorrect title

### ISSUE THREAD

**Issue by mrmckinley** [TEALSK12/apcsa-public#124]
The name of unit 4 is "Arrays, Lists, & Files", but there isn't any direct instruction on file I/O. Poster 4.1 (dealing with the File object) doesn't appear to be referenced in the curriculum either.

Should Unit 4 be renamed "Arrays and Lists"?

**Comment by aspiece** [comment]
New Units have been created to align with the College Board and resolved this issue.
