### ISSUE TITLE
Curriculum Map missing

### ISSUE THREAD

**Issue by mhoeger** [TEALSK12/apcsa-public#128]
Broken link to [Curriculum Map](https://github.com/TEALSK12/apcsa-public/tree/3b4815b12ded5bc92c608d876a9b41302a08e34a/curriculum/Curriculum-Map.md) from [AP CS A Gitbook](https://tealsk12.gitbook.io/apcsa/), under "[Using the curriculum](https://tealsk12.gitbook.io/apcsa/#using-the-curriculum)"

**Comment by aspiece** [comment]
Linked updated just waiting on the pull request to be approved.
