### ISSUE TITLE
How to access apcsa-instructor?

### ISSUE THREAD

**Issue by SebastianJay** [TEALSK12/apcsa-public#166]
The README mentions restricted curriculum materials at another repo `apcsa-instructor` but does not talk about how to gain access. I'm not authorized; what's the process?

**Comment by hawkerm** [comment]
It's the next line in the readme:

> For questions, contact [Kenney Chan](kencha@microsoft.com).

Though it could probably say *"For questions or access to the instructor repo, contact..."*

**Comment by hawkerm** [comment]
@Kenney-Chan

**Comment by SebastianJay** [comment]
Thanks. That was my guess, but I don't think it's clear as currently written.

A short description of what's in the other repo (i.e. what are "restricted curriculum materials and assets"?) might also be helpful (my guess is there are sample tests in there, but I'm not sure).

**Comment by aspiece** [comment]
Hello @SebastianJay - it looks as though you were added and have access to the Instructor Repo. You can also access the latest release of the curriculum in Additional Curriculum Materials in the TEALS Dashboard. (This contains all of the curriculum and instructor files packaged up nicely for you.)

Andrew
