### ISSUE TITLE
Issues with AP CS A curriculum, Test 2, Section II, Question 3

### ISSUE THREAD

**Issue by dmquick** [TEALSK12/apcsa-public#172]
I recently discovered a couple of issues in the AP CS A curriculum provided by teals. Specifically, AP CS  A Test 2 Section II, question 3 has both a minor problem with the questions (duplicate line), and the provided solution is incorrect (won't even compile). I'm working off the newest version of the curriculum (v2.2.2), just released December 5. Request fixes for these items. Thanks.

**Comment by aspiece** [comment]
Resolved and will be in our next release. Thank you @dmquick
