### ISSUE TITLE
Add GitBook styles/config here used to publish the actual site

### ISSUE THREAD

**Issue by hawkerm** [TEALSK12/apcsa-public#179]
Previewing the site locally doesn't contain all the styles and configuration setup for the actual [TEALS GitBook](https://tealsk12.gitbook.io/apcsa/).  e.g. Logo header and having the chapter panel on the right.

It'd be nice if we could include that config/style stuff here as well so we can have a higher fidelity preview when making changes locally.

**Comment by aspiece** [comment]
Thank you @hawkerm  We have moved to using Github Pages. https://tealsk12.github.io/apcsa-public/

The Gitbook is still active as people migrate over to this.
