### ISSUE TITLE
Broken Links - Runestone Notebook and Videos

### ISSUE THREAD

**Issue by ericatealsk12** [TEALSK12/apcsa-public#279]
Some links to the old Runestone notebook need to be updated (for example, under 2.02 and 2.03 Common Mistakes). Please make sure to update the links in the summer curriculum training course as well. 

Also, lesson videos from CS Homework Bytes under the Video section are not available, either.

**Comment by ericatealsk12** [comment]
Also, the BJC video link in 2.02 doesn't work.

**Comment by aspiece** [comment]
Links removed. I am not finding the BJC video on https://tealsk12.github.io/apcsa-public/Unit2/Lesson-202.md.html
