### ISSUE TITLE
Unit Slides are hard to discover

### ISSUE THREAD

**Issue by nathanielgranor** [TEALSK12/apcsa-public#51]
A recent Discourse post indicated that a user of the curriculum didn't know that there are slides for each unit. In particular, lesson 1.08 references the slides but the user didn't know what slides the lesson was referring to. Perhaps each lesson should link to its unit's slide deck under "materials" (or perhaps, this should only be the case if there are slides in the deck relevant to a given lesson)?

**Comment by hollasch** [comment]
Not just slides, but PDF versions of all documents as well as all lab packages. Unfortunately, TEALS is currently struggling with messaging the official curriculum release, which is kind of buried right now on the TEALS dashboard (under "Additional Curriculum Materials", through a semi-broken authentication, then under "AP CS A Release", then select the latest release).

**Comment by nathanielgranor** [comment]
I believe @kenneychan and Jeff are looking into a replacement for the SharePoint library. But perhaps any materials that we consider "main-line" and that do not contain solutions could be embedded directly within the relevant lesson plan like in the Intro curriculum?

**Comment by hollasch** [comment]
Yes, any materials that students may view and that might be useful in their studies should be made available in the curriculum, which students will also have access to. The one exception to this is generated assets (for example, PDF files from Word). These should _not_ be checked into our repo, as (1) they're large, (2) they should be generated during a formal build to guarantee consistency between source and end asset.

Product distribution is still the best solution for sharing TEALS curriculum with instructors. This ensures a consistent set of materials (cherry-picking individual assets means that teachers have a mixed version of materials that may not work together), is a much more standard way of distributing products, and guarantees that teachers have a complete set of materials at their disposal. The built file itself (a Zip archive) can be distributed through multiple channels: by hand, from the TEALS dashboard, from the GitHub release portal, and so forth.
