### ISSUE TITLE
Link to Eclipse Walkthrough no longer functions

### ISSUE THREAD

**Issue by KatherinePapcun** [TEALSK12/apcsa-public#81]
"TEALS volunteer Gil Lund has prepared a video with a Hello World and walkthrough of some Eclipse: https://mix.office.com/watch/pje5izaj92jz/."

This link just takes me to a microsoft page explaining how they've discontinued the service that the video was hosted on.

I'm hoping someone has an alternative copy of the video?

**Comment by hollasch** [comment]
This is from the README.md, Digital Tools Associated / Integrated Design Environment (IDE) - Eclipse.
