### ISSUE TITLE
Question - Practice-It

### ISSUE THREAD

**Issue by rmoscowitz** [TEALSK12/apcsa-public#84]
Do the SC and EX problems in the lessons and [curriculum map](https://tealsk12.gitbooks.io/ap-computer-science-a/content/Curriculum-Map.html) always correspond to the textbook?

I was curious, because I noticed in unit 2, the numbering of problems in the text book diverges from Practice-It. Here's an example, from the Lesson 2.02 lesson plan:

> Complete self-check questions 5, 6, 9, 12-15 (4th edition: 6, 7, 10, 14-17)

**Textbook BJP4, Chapter 2, problem 6**:

![image](https://user-images.githubusercontent.com/3596827/41830641-cb760cfc-7807-11e8-9a7a-e09c06a51232.png)

**Practice-It BJP4 2.7 (not 6!)**:

![image](https://user-images.githubusercontent.com/3596827/41830654-e54a5728-7807-11e8-950e-28e9edd824a4.png)

If the numbers in the lesson plans always correspond to the textbook, I'd be happy to open a PR with corresponding Practice-It problems. So far, I've got unit 1 and 2. https://github.com/TEALSK12/apcsa-public/compare/master...rmoscowitz:practice-it?expand=1

I just wanted to double-check that I'm reading the lesson plans correctly before going further. 

Thanks!

**Comment by nathanielgranor** [comment]
Is it possible that the issue you're seeing relates to differing editions of the BJP textbook? Which edition of the book do you have? Practice-It has problems that correspond to both the 3rd and 4th edition, sorted separately.

**Comment by rmoscowitz** [comment]
Oh gosh, I think you're right. I think I have the 4th edition textbook, but 3rd edition in PDF. Sorry about that!!
