### ISSUE TITLE
Curriculum Lesson 1.05 has bad link to "overly complicated diagram"

### ISSUE THREAD

**Issue by hollasch** [TEALSK12/apcsa-public#87]
https://tealsk12.gitbooks.io/ap-computer-science-a/content/Unit1/Lesson-105.html

tinyurl now just redirects to msn.com page.

**Comment by nathanielgranor** [comment]
I posted a number of potential replacement images in the TEALS forums.

**Comment by kenneychan** [comment]
Here's a link to the original overly complex diagram: https://d2w9rnfcy7mm78.cloudfront.net/610008/large_10de5104c65e1d586106c41ab5dd7fbd.jpg. I can create an aka.ms for update the link or we can look for a diagram that is more CS related.

**Comment by aspiece** [comment]
I update the link so it works correctly. Will leave this issue open to work on getting some alternative images.
